### ISSUE TITLE
Getting error on javascript-obfuscator-ui

### ISSUE THREAD

**Issue by I-am-Orion** [javascript-obfuscator/javascript-obfuscator-ui#34]
I'm getting error when trying to run the webpack:dev how to fix this? please help.

```
$ npm run webpack:dev

> javascript-obfuscator-web@1.3.1 webpack:dev /data/data/com.termux/files/home/jsui
> webpack --mode development --config webpack.conf.js --watch --color --progress

/data/data/com.termux/files/home/jsui/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/data/data/com.termux/files/home/jsui/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /data/data/com.termux/files/home/jsui/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/data/data/com.termux/files/home/jsui/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/data/data/com.termux/files/home/jsui/node_modules/webpack/bin/webpack.js:156:2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-obfuscator-web@1.3.1 webpack:dev: `webpack --mode development --config webpack.conf.js --watch --color --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-obfuscator-web@1.3.1 webpack:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-04-29T04_26_54_520Z-debug.log
```

**Comment by sanex3339** [comment]
Closed as old. Fell free to create a new issue if this problem still exists.
