### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by onelsonic** [javascript-obfuscator/javascript-obfuscator-ui#55]
n/a

**Comment by sanex3339** [comment]
How to reproduce this error?

**Comment by onelsonic** [comment]
it occurs when installing javascript-obfuscator-ui on win10 using nodejs v14.12.0

**Comment by onelsonic** [comment]
all the steps on windows10 :

```
npm install -g win-node-env
git clone https://github.com/javascript-obfuscator/javascript-obfuscator-ui.git
cd javascript-obfuscator-ui
```

edit package.json :
~~~~
"postinstall": "npm run updatesemantic && npm run webpack:prod",
"updatesemantic": "cp App/styles/theme.config ./node_modules/semantic-ui-less/theme.config; rm -Rf ./node_modules/semantic-ui-less/site; cp -R App/styles/site ./node_modules/semantic-ui-less/"
~~~~
to
~~~~
"postinstall": "echo step1 done"
~~~~

then building the react project:
```
npm install
copy App\styles\theme.config node_modules\semantic-ui-less\theme.config && Xcopy /E /I /Q /S App\styles\site node_modules\semantic-ui-less\site
npm run webpack:prod
```

Running the express server:
`node server.js`


you will then get the error : 
```
C:\nodejs\javascript-obfuscator-ui>node server.js
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist' is not defined by "exports" in C:\nodejs\javascript-obfuscator-ui\node_modules\threads\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:496:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\nodejs\javascript-obfuscator-ui\server.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1076:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

it works fine on linux, but just trying to run it on windows10.
